# Node.js 20 이미지를 사용
FROM node:20-alpine

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# package.json과 package-lock.json 복사
COPY krampoline/package*.json ./

# 의존성 설치
RUN npm install

# 소스 코드 복사
COPY krampoline/ ./

# React 개발 서버 실행
CMD ["npm", "start"]

# React 개발 서버 포트 노출
EXPOSE 3000

