name: Deploy React App via Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t react-app:latest -f Dockerfile_A .

      # Step 4: Deploy to CentOS 8 Server
      - name: Deploy to CentOS 8 Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            sudo docker stop react-app1 || true
            sudo docker rm react-app || true
            sudo docker rmi react-app:latest || true
            sudo docker build -t react-app:latest -f Dockerfile_A .
            sudo docker run -d -p 3000:3000 --name react-app1 react-app:latest
