name: React App Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t react-app:latest -f Dockerfile_A .

      # Deploy to CentOS 8 Server
      - name: Deploy to CentOS 8
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: goormtago
          password: 1234
          port: 22
          script: |
            # Stop and remove the existing container if it exists
            sudo docker stop react-app1 || true
            sudo docker rm react-app1 || true

            # Build and run the new container
            sudo docker pull react-app:latest
            sudo docker run -d -p 3000:3000 --name react-app1 react-app:latest
