name: Deploy React App via Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Parse Secrets
      - name: Parse Connection Secrets
        id: parse_secrets
        run: |
          echo "::set-output name=host::$(echo '${{ secrets.OCI_CENTOS8_GOORMTAGO }}' | jq -r '.host')"
          echo "::set-output name=port::$(echo '${{ secrets.OCI_CENTOS8_GOORMTAGO }}' | jq -r '.port')"
          echo "::set-output name=username::$(echo '${{ secrets.OCI_CENTOS8_GOORMTAGO }}' | jq -r '.username')"
          echo "::set-output name=password::$(echo '${{ secrets.OCI_CENTOS8_GOORMTAGO }}' | jq -r '.password')"

      # Step 4: Deploy to CentOS 8 Server
      - name: Deploy to CentOS 8 Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ steps.parse_secrets.outputs.host }}
          port: ${{ steps.parse_secrets.outputs.port }}
          username: ${{ steps.parse_secrets.outputs.username }}
          password: ${{ steps.parse_secrets.outputs.password }}
          script: |
            # Move to the project directory
            cd /home/goormtago/goorm-tago-frontend

            # Pull the latest code from the repository
            git reset --hard
            git pull origin main

            # Stop and remove the existing container
            sudo docker stop react-app || true
            sudo docker rm react-app || true

            # Remove the old Docker image (if exists)
            sudo docker rmi react-app:latest || true

            # Build and run the Docker container
            sudo docker build -t react-app:latest -f Dockerfile_A .
            sudo docker run -d -p 3000:3000 --name react-app react-app:latest
